name: Beta to Pre-Release Promotion

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 25.04)'
        required: true
        type: string

jobs:
  move-beta-to-pre-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Promote Beta to Stable and Update Pre-Release
      run: |
        VERSION="${{ inputs.version }}"
        echo "Promoting Beta to Stable and updating Pre-Release for version $VERSION"

        mkdir -p grids/$VERSION
        mv grids/${VERSION}-beta/* grids/$VERSION/

        mv grids/$VERSION/rom_grid3d_${VERSION}-beta.spg grids/$VERSION/rom_grid3d_${VERSION}.spg

        rm -rf grids/${VERSION}-beta
        rm -rf grids/pre-release

        mkdir -p grids/pre-release
        cp grids/$VERSION/* grids/pre-release/

        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add grids/
        git commit -m "Promoted Beta to Stable and Updated Pre-Release for version $VERSION"
        git push
