name: D. Promote Pre-Release to Latest

on:
  workflow_dispatch:

jobs:
  prerelease-to-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir -p grids/latest
          cp grids/pre-release/metadata.json grids/latest/metadata.json
          
          # Copy .spg file
          spg_src=$(ls grids/pre-release/rom_grid3d_*.spg | head -n 1)
          cp "$spg_src" grids/latest/rom_grid3d_latest.spg
          
          # Copy .json file if present
          json_src=$(ls grids/pre-release/rom_grid3d_*.json 2>/dev/null | head -n 1 || true)
          if [ -n "$json_src" ]; then
            cp "$json_src" grids/latest/rom_grid3d_latest.json
          fi
          
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add grids/latest
          git commit -m "Updated latest from pre-release"
          git push
